# Generated by Django 4.1.4 on 2022-12-30 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_submission_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_auto_20171017_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='instructor.course'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='instructor.course'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='instructor.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
